# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ABUNCHA-RANDOM
description: Photography // Food // Blogs
baseurl: "/abrandom-site" # the subpath of your site, e.g. /blog

port: 6969

# Build settings
markdown: kramdown

sass:
  # loading path from site root
  # default to _sass
  sass_dir: assets/css
  style: :nested
